package com.github.cnrture.quickbackendwizard.contents

fun getServiceContent(
    packageName: String,
    entityName: String,
    serviceName: String,
    repositoryName: String,
): String {
    return buildString {
        appendLine("package $packageName.service")
        appendLine()
        appendLine("import $packageName.common.ApiResponse")
        appendLine("import $packageName.entity.$entityName")
        appendLine("import $packageName.repository.$repositoryName")
        appendLine("import org.slf4j.LoggerFactory")
        appendLine("import org.springframework.stereotype.Service")
        appendLine("import org.springframework.transaction.annotation.Transactional")
        appendLine()
        appendLine("@Service")
        appendLine("@Transactional(readOnly = true)")
        appendLine("class $serviceName(private val repository: $repositoryName) {")
        appendLine()
        appendLine("    private val logger = LoggerFactory.getLogger($serviceName::class.java)")
        appendLine()
        appendLine("    fun getAll(): ApiResponse<List<$entityName>> {")
        appendLine("        logger.debug(\"Fetching all $entityName entities\")")
        appendLine("        try {")
        appendLine("            val entities = repository.findAll()")
        appendLine("            logger.info(\"Successfully fetched \${entities.size} $entityName entities\")")
        appendLine("            return ApiResponse(")
        appendLine("                success = true,")
        appendLine("                message = \"Successfully fetched $entityName list\",")
        appendLine("                data = entities,")
        appendLine("            )")
        appendLine("        } catch (e: Exception) {")
        appendLine("            logger.error(\"Error fetching $entityName list: \${e.message}\", e)")
        appendLine("            return ApiResponse(")
        appendLine("                success = false,")
        appendLine("                message = \"Error fetching $entityName list: \${e.message}\",")
        appendLine("                data = emptyList(),")
        appendLine("            )")
        appendLine("        }")
        appendLine("    }")
        appendLine()
        appendLine("    fun getById(id: Long): ApiResponse<$entityName> {")
        appendLine("        logger.debug(\"Fetching $entityName with id: \$id\")")
        appendLine("        try {")
        appendLine("            val entity = repository.findById(id).orElseThrow { ")
        appendLine("                NoSuchElementException(\"$entityName not found with id: \$id\") ")
        appendLine("            }")
        appendLine("            logger.info(\"Successfully fetched $entityName with id: \$id\")")
        appendLine("            return ApiResponse(")
        appendLine("                success = true,")
        appendLine("                message = \"Successfully fetched $entityName\",")
        appendLine("                data = entity,")
        appendLine("            )")
        appendLine("        } catch (e: NoSuchElementException) {")
        appendLine("            logger.warn(\"$entityName not found with id: \$id\")")
        appendLine("            return ApiResponse(")
        appendLine("                success = false,")
        appendLine("                message = e.message ?: \"No such element\",")
        appendLine("                data = null,")
        appendLine("            )")
        appendLine("        } catch (e: Exception) {")
        appendLine("            logger.error(\"Error fetching $entityName with id \$id: \${e.message}\", e)")
        appendLine("            return ApiResponse(")
        appendLine("                success = false,")
        appendLine("                message = \"Error fetching $entityName: \${e.message}\",")
        appendLine("                data = null,")
        appendLine("            )")
        appendLine("        }")
        appendLine("    }")
        appendLine()
        appendLine("    @Transactional")
        appendLine("    fun create(entity: $entityName): ApiResponse<$entityName> {")
        appendLine("        logger.debug(\"Creating new $entityName\")")
        appendLine("        return try {")
        appendLine("            val savedEntity = repository.save(entity)")
        appendLine("            logger.info(\"Successfully created $entityName with id: \${savedEntity.id}\")")
        appendLine("            ApiResponse(")
        appendLine("                success = true,")
        appendLine("                message = \"$entityName created successfully\",")
        appendLine("                data = savedEntity,")
        appendLine("            )")
        appendLine("        } catch (e: Exception) {")
        appendLine("            logger.error(\"Error creating $entityName: \${e.message}\", e)")
        appendLine("            ApiResponse(")
        appendLine("                success = false,")
        appendLine("                message = \"Error creating $entityName: \${e.message}\",")
        appendLine("                data = null,")
        appendLine("            )")
        appendLine("        }")
        appendLine("    }")
        appendLine()
        appendLine("    @Transactional")
        appendLine("    fun update(id: Long, entity: $entityName): ApiResponse<$entityName> {")
        appendLine("        logger.debug(\"Updating $entityName with id: \$id\")")
        appendLine("        return try {")
        appendLine("            if (!repository.existsById(id)) {")
        appendLine("                logger.warn(\"$entityName not found with id: \$id for update\")")
        appendLine("                return ApiResponse(")
        appendLine("                    success = false,")
        appendLine("                    message = \"$entityName not found with id: \$id\",")
        appendLine("                    data = null,")
        appendLine("                )")
        appendLine("            }")
        appendLine("            val updatedEntity = repository.save(entity.copy(id = id))")
        appendLine("            logger.info(\"Successfully updated $entityName with id: \$id\")")
        appendLine("            ApiResponse(")
        appendLine("                success = true,")
        appendLine("                message = \"$entityName updated successfully\",")
        appendLine("                data = updatedEntity,")
        appendLine("            )")
        appendLine("        } catch (e: Exception) {")
        appendLine("            logger.error(\"Error updating $entityName with id \$id: \${e.message}\", e)")
        appendLine("            ApiResponse(")
        appendLine("                success = false,")
        appendLine("                message = \"Error updating $entityName: \${e.message}\",")
        appendLine("                data = null,")
        appendLine("            )")
        appendLine("        }")
        appendLine("    }")
        appendLine()
        appendLine("    @Transactional")
        appendLine("    fun deleteById(id: Long): ApiResponse<Boolean> {")
        appendLine("        logger.debug(\"Deleting $entityName with id: \$id\")")
        appendLine("        return try {")
        appendLine("            if (!repository.existsById(id)) {")
        appendLine("                logger.warn(\"$entityName not found with id: \$id for deletion\")")
        appendLine("                return ApiResponse(")
        appendLine("                    success = false,")
        appendLine("                    message = \"$entityName not found with id: \$id\",")
        appendLine("                    data = false,")
        appendLine("                )")
        appendLine("            }")
        appendLine("            repository.deleteById(id)")
        appendLine("            logger.info(\"Successfully deleted $entityName with id: \$id\")")
        appendLine("            ApiResponse(")
        appendLine("                success = true,")
        appendLine("                message = \"$entityName deleted successfully\",")
        appendLine("                data = true,")
        appendLine("            )")
        appendLine("        } catch (e: Exception) {")
        appendLine("            logger.error(\"Error deleting $entityName with id \$id: \${e.message}\", e)")
        appendLine("            ApiResponse(")
        appendLine("                success = false,")
        appendLine("                message = \"Error deleting $entityName: \${e.message}\",")
        appendLine("                data = false,")
        appendLine("            )")
        appendLine("        }")
        appendLine("    }")
        appendLine("}")
    }
}